// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/product/:id": {
    params: {
      "id": string;
    };
  };
  "/cart": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/checkout": {
    params: {};
  };
  "/checkout/success/:orderId": {
    params: {
      "orderId": string;
    };
  };
  "/about": {
    params: {};
  };
  "/shipping": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/profile": {
    params: {};
  };
  "/maintenance": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/admin/orders": {
    params: {};
  };
  "/admin/orders/:id": {
    params: {
      "id": string;
    };
  };
  "/admin/email-logs": {
    params: {};
  };
  "/admin/inventory": {
    params: {};
  };
  "/admin/marketing": {
    params: {};
  };
  "/admin/seed": {
    params: {};
  };
  "/admin/analytics": {
    params: {};
  };
  "/admin/invitations": {
    params: {};
  };
  "/admin/storefront": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/product/:id" | "/cart" | "/login" | "/checkout" | "/checkout/success/:orderId" | "/about" | "/shipping" | "/contact" | "/profile" | "/maintenance" | "/admin" | "/admin/orders" | "/admin/orders/:id" | "/admin/email-logs" | "/admin/inventory" | "/admin/marketing" | "/admin/seed" | "/admin/analytics" | "/admin/invitations" | "/admin/storefront";
  };
  "../src/pages/Home.tsx": {
    id: "../src/pages/Home";
    page: "/";
  };
  "../src/pages/ProductDetail.tsx": {
    id: "../src/pages/ProductDetail";
    page: "/product/:id";
  };
  "../src/pages/Cart.tsx": {
    id: "../src/pages/Cart";
    page: "/cart";
  };
  "../src/pages/Login.tsx": {
    id: "../src/pages/Login";
    page: "/login";
  };
  "../src/pages/Checkout.tsx": {
    id: "../src/pages/Checkout";
    page: "/checkout";
  };
  "../src/pages/Success.tsx": {
    id: "../src/pages/Success";
    page: "/checkout/success/:orderId";
  };
  "../src/pages/Static/InfoPages.tsx": {
    id: "about";
    page: "/about";
  } | {
    id: "shipping";
    page: "/shipping";
  } | {
    id: "contact";
    page: "/contact";
  };
  "../src/pages/Profile.tsx": {
    id: "../src/pages/Profile";
    page: "/profile";
  };
  "../src/pages/Static/Maintenance.tsx": {
    id: "../src/pages/Static/Maintenance";
    page: "/maintenance";
  };
  "../src/components/layout/AdminLayout.tsx": {
    id: "../src/components/layout/AdminLayout";
    page: "/admin" | "/admin/orders" | "/admin/orders/:id" | "/admin/email-logs" | "/admin/inventory" | "/admin/marketing" | "/admin/seed" | "/admin/analytics" | "/admin/invitations" | "/admin/storefront";
  };
  "../src/pages/Admin/Orders.tsx": {
    id: "admin-index";
    page: "/admin";
  } | {
    id: "admin-orders-list";
    page: "/admin/orders";
  };
  "../src/pages/Admin/OrderDetail.tsx": {
    id: "../src/pages/Admin/OrderDetail";
    page: "/admin/orders/:id";
  };
  "../src/pages/Admin/EmailLogs.tsx": {
    id: "../src/pages/Admin/EmailLogs";
    page: "/admin/email-logs";
  };
  "../src/pages/Admin/Inventory.tsx": {
    id: "../src/pages/Admin/Inventory";
    page: "/admin/inventory";
  };
  "../src/pages/Admin/Marketing.tsx": {
    id: "../src/pages/Admin/Marketing";
    page: "/admin/marketing";
  };
  "../src/pages/Admin/SeedData.tsx": {
    id: "../src/pages/Admin/SeedData";
    page: "/admin/seed";
  };
  "../src/pages/Admin/Analytics.tsx": {
    id: "../src/pages/Admin/Analytics";
    page: "/admin/analytics";
  };
  "../src/pages/Admin/Invitations.tsx": {
    id: "../src/pages/Admin/Invitations";
    page: "/admin/invitations";
  };
  "../src/pages/Admin/Storefront.tsx": {
    id: "../src/pages/Admin/Storefront";
    page: "/admin/storefront";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "../src/pages/Home": unknown;
  "../src/pages/ProductDetail": unknown;
  "../src/pages/Cart": unknown;
  "../src/pages/Login": unknown;
  "../src/pages/Checkout": unknown;
  "../src/pages/Success": unknown;
  "about": unknown;
  "shipping": unknown;
  "contact": unknown;
  "../src/pages/Profile": unknown;
  "../src/pages/Static/Maintenance": unknown;
  "../src/components/layout/AdminLayout": unknown;
  "admin-index": unknown;
  "admin-orders-list": unknown;
  "../src/pages/Admin/OrderDetail": unknown;
  "../src/pages/Admin/EmailLogs": unknown;
  "../src/pages/Admin/Inventory": unknown;
  "../src/pages/Admin/Marketing": unknown;
  "../src/pages/Admin/SeedData": unknown;
  "../src/pages/Admin/Analytics": unknown;
  "../src/pages/Admin/Invitations": unknown;
  "../src/pages/Admin/Storefront": unknown;
};